/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedWorkerSubscriptionRouteImport } from './routes/_authenticated/worker.subscription'
import { Route as AuthenticatedWorkerOnboardingRouteImport } from './routes/_authenticated/worker.onboarding'
import { Route as AuthenticatedWorkerJobsRouteImport } from './routes/_authenticated/worker.jobs'
import { Route as AuthenticatedWorkerDashboardRouteImport } from './routes/_authenticated/worker.dashboard'
import { Route as AuthenticatedWorkerApplicationsRouteImport } from './routes/_authenticated/worker.applications'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsMineRouteImport } from './routes/_authenticated/jobs.mine'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedChatBookingIdRouteImport } from './routes/_authenticated/chat.$bookingId'
import { Route as AuthenticatedBookWorkerIdRouteImport } from './routes/_authenticated/book.$workerId'
import { Route as AuthenticatedAdminWorkersRouteImport } from './routes/_authenticated/admin.workers'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin.jobs.index'
import { Route as AuthenticatedJobsIdEditRouteImport } from './routes/_authenticated/jobs.$id.edit'
import { Route as AuthenticatedJobsIdApplyRouteImport } from './routes/_authenticated/jobs.$id.apply'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as AuthenticatedAdminJobsJobIdRouteImport } from './routes/_authenticated/admin.jobs.$jobId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedWorkerSubscriptionRoute =
  AuthenticatedWorkerSubscriptionRouteImport.update({
    id: '/worker/subscription',
    path: '/worker/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerOnboardingRoute =
  AuthenticatedWorkerOnboardingRouteImport.update({
    id: '/worker/onboarding',
    path: '/worker/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerJobsRoute = AuthenticatedWorkerJobsRouteImport.update({
  id: '/worker/jobs',
  path: '/worker/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerDashboardRoute =
  AuthenticatedWorkerDashboardRouteImport.update({
    id: '/worker/dashboard',
    path: '/worker/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerApplicationsRoute =
  AuthenticatedWorkerApplicationsRouteImport.update({
    id: '/worker/applications',
    path: '/worker/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsMineRoute = AuthenticatedJobsMineRouteImport.update({
  id: '/jobs/mine',
  path: '/jobs/mine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatBookingIdRoute =
  AuthenticatedChatBookingIdRouteImport.update({
    id: '/chat/$bookingId',
    path: '/chat/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookWorkerIdRoute =
  AuthenticatedBookWorkerIdRouteImport.update({
    id: '/book/$workerId',
    path: '/book/$workerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWorkersRoute =
  AuthenticatedAdminWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminJobsRoute,
  } as any)
const AuthenticatedJobsIdEditRoute = AuthenticatedJobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedJobsIdRoute,
} as any)
const AuthenticatedJobsIdApplyRoute =
  AuthenticatedJobsIdApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => AuthenticatedJobsIdRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsJobIdRoute =
  AuthenticatedAdminJobsJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AuthenticatedAdminJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/': typeof WorkersIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRouteWithChildren
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/worker/applications': typeof AuthenticatedWorkerApplicationsRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/jobs/$id/apply': typeof AuthenticatedJobsIdApplyRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers': typeof WorkersIndexRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/worker/applications': typeof AuthenticatedWorkerApplicationsRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/jobs/$id/apply': typeof AuthenticatedJobsIdApplyRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/workers/$id': typeof WorkersIdRoute
  '/workers/': typeof WorkersIndexRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRouteWithChildren
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/workers': typeof AuthenticatedAdminWorkersRoute
  '/_authenticated/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/_authenticated/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/_authenticated/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/worker/applications': typeof AuthenticatedWorkerApplicationsRoute
  '/_authenticated/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/_authenticated/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/_authenticated/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/_authenticated/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/jobs/$id/apply': typeof AuthenticatedJobsIdApplyRoute
  '/_authenticated/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/admin'
    | '/bookings'
    | '/notifications'
    | '/support'
    | '/admin/login'
    | '/workers/$id'
    | '/workers/'
    | '/admin/bookings'
    | '/admin/jobs'
    | '/admin/support'
    | '/admin/workers'
    | '/book/$workerId'
    | '/chat/$bookingId'
    | '/jobs/$id'
    | '/jobs/mine'
    | '/jobs/new'
    | '/worker/applications'
    | '/worker/dashboard'
    | '/worker/jobs'
    | '/worker/onboarding'
    | '/worker/subscription'
    | '/admin/'
    | '/jobs/'
    | '/admin/jobs/$jobId'
    | '/admin/users/$userId'
    | '/jobs/$id/apply'
    | '/jobs/$id/edit'
    | '/admin/jobs/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/bookings'
    | '/notifications'
    | '/support'
    | '/admin/login'
    | '/workers/$id'
    | '/workers'
    | '/admin/bookings'
    | '/admin/support'
    | '/admin/workers'
    | '/book/$workerId'
    | '/chat/$bookingId'
    | '/jobs/$id'
    | '/jobs/mine'
    | '/jobs/new'
    | '/worker/applications'
    | '/worker/dashboard'
    | '/worker/jobs'
    | '/worker/onboarding'
    | '/worker/subscription'
    | '/admin'
    | '/jobs'
    | '/admin/jobs/$jobId'
    | '/admin/users/$userId'
    | '/jobs/$id/apply'
    | '/jobs/$id/edit'
    | '/admin/jobs'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/profile'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/notifications'
    | '/_authenticated/support'
    | '/admin/login'
    | '/workers/$id'
    | '/workers/'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/workers'
    | '/_authenticated/book/$workerId'
    | '/_authenticated/chat/$bookingId'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/jobs/mine'
    | '/_authenticated/jobs/new'
    | '/_authenticated/worker/applications'
    | '/_authenticated/worker/dashboard'
    | '/_authenticated/worker/jobs'
    | '/_authenticated/worker/onboarding'
    | '/_authenticated/worker/subscription'
    | '/_authenticated/admin/'
    | '/_authenticated/jobs/'
    | '/_authenticated/admin/jobs/$jobId'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/jobs/$id/apply'
    | '/_authenticated/jobs/$id/edit'
    | '/_authenticated/admin/jobs/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  WorkersIdRoute: typeof WorkersIdRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/worker/subscription': {
      id: '/_authenticated/worker/subscription'
      path: '/worker/subscription'
      fullPath: '/worker/subscription'
      preLoaderRoute: typeof AuthenticatedWorkerSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/onboarding': {
      id: '/_authenticated/worker/onboarding'
      path: '/worker/onboarding'
      fullPath: '/worker/onboarding'
      preLoaderRoute: typeof AuthenticatedWorkerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/jobs': {
      id: '/_authenticated/worker/jobs'
      path: '/worker/jobs'
      fullPath: '/worker/jobs'
      preLoaderRoute: typeof AuthenticatedWorkerJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/dashboard': {
      id: '/_authenticated/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/applications': {
      id: '/_authenticated/worker/applications'
      path: '/worker/applications'
      fullPath: '/worker/applications'
      preLoaderRoute: typeof AuthenticatedWorkerApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/mine': {
      id: '/_authenticated/jobs/mine'
      path: '/jobs/mine'
      fullPath: '/jobs/mine'
      preLoaderRoute: typeof AuthenticatedJobsMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$bookingId': {
      id: '/_authenticated/chat/$bookingId'
      path: '/chat/$bookingId'
      fullPath: '/chat/$bookingId'
      preLoaderRoute: typeof AuthenticatedChatBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$workerId': {
      id: '/_authenticated/book/$workerId'
      path: '/book/$workerId'
      fullPath: '/book/$workerId'
      preLoaderRoute: typeof AuthenticatedBookWorkerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/workers': {
      id: '/_authenticated/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AuthenticatedAdminWorkersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminJobsRoute
    }
    '/_authenticated/jobs/$id/edit': {
      id: '/_authenticated/jobs/$id/edit'
      path: '/edit'
      fullPath: '/jobs/$id/edit'
      preLoaderRoute: typeof AuthenticatedJobsIdEditRouteImport
      parentRoute: typeof AuthenticatedJobsIdRoute
    }
    '/_authenticated/jobs/$id/apply': {
      id: '/_authenticated/jobs/$id/apply'
      path: '/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof AuthenticatedJobsIdApplyRouteImport
      parentRoute: typeof AuthenticatedJobsIdRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/$jobId': {
      id: '/_authenticated/admin/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAdminJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAdminJobsRoute
    }
  }
}

interface AuthenticatedAdminJobsRouteChildren {
  AuthenticatedAdminJobsJobIdRoute: typeof AuthenticatedAdminJobsJobIdRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
}

const AuthenticatedAdminJobsRouteChildren: AuthenticatedAdminJobsRouteChildren =
  {
    AuthenticatedAdminJobsJobIdRoute: AuthenticatedAdminJobsJobIdRoute,
    AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
  }

const AuthenticatedAdminJobsRouteWithChildren =
  AuthenticatedAdminJobsRoute._addFileChildren(
    AuthenticatedAdminJobsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRouteWithChildren
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminWorkersRoute: typeof AuthenticatedAdminWorkersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRouteWithChildren,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminWorkersRoute: AuthenticatedAdminWorkersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJobsIdRouteChildren {
  AuthenticatedJobsIdApplyRoute: typeof AuthenticatedJobsIdApplyRoute
  AuthenticatedJobsIdEditRoute: typeof AuthenticatedJobsIdEditRoute
}

const AuthenticatedJobsIdRouteChildren: AuthenticatedJobsIdRouteChildren = {
  AuthenticatedJobsIdApplyRoute: AuthenticatedJobsIdApplyRoute,
  AuthenticatedJobsIdEditRoute: AuthenticatedJobsIdEditRoute,
}

const AuthenticatedJobsIdRouteWithChildren =
  AuthenticatedJobsIdRoute._addFileChildren(AuthenticatedJobsIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedBookWorkerIdRoute: typeof AuthenticatedBookWorkerIdRoute
  AuthenticatedChatBookingIdRoute: typeof AuthenticatedChatBookingIdRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRouteWithChildren
  AuthenticatedJobsMineRoute: typeof AuthenticatedJobsMineRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedWorkerApplicationsRoute: typeof AuthenticatedWorkerApplicationsRoute
  AuthenticatedWorkerDashboardRoute: typeof AuthenticatedWorkerDashboardRoute
  AuthenticatedWorkerJobsRoute: typeof AuthenticatedWorkerJobsRoute
  AuthenticatedWorkerOnboardingRoute: typeof AuthenticatedWorkerOnboardingRoute
  AuthenticatedWorkerSubscriptionRoute: typeof AuthenticatedWorkerSubscriptionRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedBookWorkerIdRoute: AuthenticatedBookWorkerIdRoute,
  AuthenticatedChatBookingIdRoute: AuthenticatedChatBookingIdRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRouteWithChildren,
  AuthenticatedJobsMineRoute: AuthenticatedJobsMineRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedWorkerApplicationsRoute: AuthenticatedWorkerApplicationsRoute,
  AuthenticatedWorkerDashboardRoute: AuthenticatedWorkerDashboardRoute,
  AuthenticatedWorkerJobsRoute: AuthenticatedWorkerJobsRoute,
  AuthenticatedWorkerOnboardingRoute: AuthenticatedWorkerOnboardingRoute,
  AuthenticatedWorkerSubscriptionRoute: AuthenticatedWorkerSubscriptionRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  WorkersIdRoute: WorkersIdRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
