/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedWorkerSubscriptionRouteImport } from './routes/_authenticated/worker.subscription'
import { Route as AuthenticatedWorkerOnboardingRouteImport } from './routes/_authenticated/worker.onboarding'
import { Route as AuthenticatedWorkerJobsRouteImport } from './routes/_authenticated/worker.jobs'
import { Route as AuthenticatedWorkerDashboardRouteImport } from './routes/_authenticated/worker.dashboard'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsMineRouteImport } from './routes/_authenticated/jobs.mine'
import { Route as AuthenticatedJobsIdRouteImport } from './routes/_authenticated/jobs.$id'
import { Route as AuthenticatedChatBookingIdRouteImport } from './routes/_authenticated/chat.$bookingId'
import { Route as AuthenticatedBookWorkerIdRouteImport } from './routes/_authenticated/book.$workerId'
import { Route as AuthenticatedJobsIdEditRouteImport } from './routes/_authenticated/jobs.$id.edit'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkersRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerSubscriptionRoute =
  AuthenticatedWorkerSubscriptionRouteImport.update({
    id: '/worker/subscription',
    path: '/worker/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerOnboardingRoute =
  AuthenticatedWorkerOnboardingRouteImport.update({
    id: '/worker/onboarding',
    path: '/worker/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerJobsRoute = AuthenticatedWorkerJobsRouteImport.update({
  id: '/worker/jobs',
  path: '/worker/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkerDashboardRoute =
  AuthenticatedWorkerDashboardRouteImport.update({
    id: '/worker/dashboard',
    path: '/worker/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsMineRoute = AuthenticatedJobsMineRouteImport.update({
  id: '/jobs/mine',
  path: '/jobs/mine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIdRoute = AuthenticatedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatBookingIdRoute =
  AuthenticatedChatBookingIdRouteImport.update({
    id: '/chat/$bookingId',
    path: '/chat/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookWorkerIdRoute =
  AuthenticatedBookWorkerIdRouteImport.update({
    id: '/book/$workerId',
    path: '/book/$workerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIdEditRoute = AuthenticatedJobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/workers': typeof WorkersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/workers/$id': typeof WorkersIdRoute
  '/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/workers': typeof WorkersRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/workers/$id': typeof WorkersIdRoute
  '/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/workers': typeof WorkersRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/workers/$id': typeof WorkersIdRoute
  '/_authenticated/book/$workerId': typeof AuthenticatedBookWorkerIdRoute
  '/_authenticated/chat/$bookingId': typeof AuthenticatedChatBookingIdRoute
  '/_authenticated/jobs/$id': typeof AuthenticatedJobsIdRouteWithChildren
  '/_authenticated/jobs/mine': typeof AuthenticatedJobsMineRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/worker/dashboard': typeof AuthenticatedWorkerDashboardRoute
  '/_authenticated/worker/jobs': typeof AuthenticatedWorkerJobsRoute
  '/_authenticated/worker/onboarding': typeof AuthenticatedWorkerOnboardingRoute
  '/_authenticated/worker/subscription': typeof AuthenticatedWorkerSubscriptionRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/jobs/$id/edit': typeof AuthenticatedJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/workers'
    | '/admin'
    | '/bookings'
    | '/workers/$id'
    | '/book/$workerId'
    | '/chat/$bookingId'
    | '/jobs/$id'
    | '/jobs/mine'
    | '/jobs/new'
    | '/worker/dashboard'
    | '/worker/jobs'
    | '/worker/onboarding'
    | '/worker/subscription'
    | '/jobs/'
    | '/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/workers'
    | '/admin'
    | '/bookings'
    | '/workers/$id'
    | '/book/$workerId'
    | '/chat/$bookingId'
    | '/jobs/$id'
    | '/jobs/mine'
    | '/jobs/new'
    | '/worker/dashboard'
    | '/worker/jobs'
    | '/worker/onboarding'
    | '/worker/subscription'
    | '/jobs'
    | '/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/profile'
    | '/workers'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/workers/$id'
    | '/_authenticated/book/$workerId'
    | '/_authenticated/chat/$bookingId'
    | '/_authenticated/jobs/$id'
    | '/_authenticated/jobs/mine'
    | '/_authenticated/jobs/new'
    | '/_authenticated/worker/dashboard'
    | '/_authenticated/worker/jobs'
    | '/_authenticated/worker/onboarding'
    | '/_authenticated/worker/subscription'
    | '/_authenticated/jobs/'
    | '/_authenticated/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  WorkersRoute: typeof WorkersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/subscription': {
      id: '/_authenticated/worker/subscription'
      path: '/worker/subscription'
      fullPath: '/worker/subscription'
      preLoaderRoute: typeof AuthenticatedWorkerSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/onboarding': {
      id: '/_authenticated/worker/onboarding'
      path: '/worker/onboarding'
      fullPath: '/worker/onboarding'
      preLoaderRoute: typeof AuthenticatedWorkerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/jobs': {
      id: '/_authenticated/worker/jobs'
      path: '/worker/jobs'
      fullPath: '/worker/jobs'
      preLoaderRoute: typeof AuthenticatedWorkerJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/dashboard': {
      id: '/_authenticated/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/mine': {
      id: '/_authenticated/jobs/mine'
      path: '/jobs/mine'
      fullPath: '/jobs/mine'
      preLoaderRoute: typeof AuthenticatedJobsMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id': {
      id: '/_authenticated/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthenticatedJobsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$bookingId': {
      id: '/_authenticated/chat/$bookingId'
      path: '/chat/$bookingId'
      fullPath: '/chat/$bookingId'
      preLoaderRoute: typeof AuthenticatedChatBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$workerId': {
      id: '/_authenticated/book/$workerId'
      path: '/book/$workerId'
      fullPath: '/book/$workerId'
      preLoaderRoute: typeof AuthenticatedBookWorkerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$id/edit': {
      id: '/_authenticated/jobs/$id/edit'
      path: '/edit'
      fullPath: '/jobs/$id/edit'
      preLoaderRoute: typeof AuthenticatedJobsIdEditRouteImport
      parentRoute: typeof AuthenticatedJobsIdRoute
    }
  }
}

interface AuthenticatedJobsIdRouteChildren {
  AuthenticatedJobsIdEditRoute: typeof AuthenticatedJobsIdEditRoute
}

const AuthenticatedJobsIdRouteChildren: AuthenticatedJobsIdRouteChildren = {
  AuthenticatedJobsIdEditRoute: AuthenticatedJobsIdEditRoute,
}

const AuthenticatedJobsIdRouteWithChildren =
  AuthenticatedJobsIdRoute._addFileChildren(AuthenticatedJobsIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBookWorkerIdRoute: typeof AuthenticatedBookWorkerIdRoute
  AuthenticatedChatBookingIdRoute: typeof AuthenticatedChatBookingIdRoute
  AuthenticatedJobsIdRoute: typeof AuthenticatedJobsIdRouteWithChildren
  AuthenticatedJobsMineRoute: typeof AuthenticatedJobsMineRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedWorkerDashboardRoute: typeof AuthenticatedWorkerDashboardRoute
  AuthenticatedWorkerJobsRoute: typeof AuthenticatedWorkerJobsRoute
  AuthenticatedWorkerOnboardingRoute: typeof AuthenticatedWorkerOnboardingRoute
  AuthenticatedWorkerSubscriptionRoute: typeof AuthenticatedWorkerSubscriptionRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBookWorkerIdRoute: AuthenticatedBookWorkerIdRoute,
  AuthenticatedChatBookingIdRoute: AuthenticatedChatBookingIdRoute,
  AuthenticatedJobsIdRoute: AuthenticatedJobsIdRouteWithChildren,
  AuthenticatedJobsMineRoute: AuthenticatedJobsMineRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedWorkerDashboardRoute: AuthenticatedWorkerDashboardRoute,
  AuthenticatedWorkerJobsRoute: AuthenticatedWorkerJobsRoute,
  AuthenticatedWorkerOnboardingRoute: AuthenticatedWorkerOnboardingRoute,
  AuthenticatedWorkerSubscriptionRoute: AuthenticatedWorkerSubscriptionRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WorkersRouteChildren {
  WorkersIdRoute: typeof WorkersIdRoute
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersIdRoute: WorkersIdRoute,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  WorkersRoute: WorkersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
